spring:
  datasource:
    url: jdbc:h2:file:./data
    username: user
    password: pass
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

app:
  base: EUR
  adapters:
    currency:
      endpoint: https://api.exchangerate.host/
